import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { container, box, imageStyle, title, description, text, infoBlock, contactContainer, icon, link } from './about.content.style'; // виправлено 'titel' на 'title'
import Pexels from '../../../../assets/pexels-pixabay.png';
import IconPhone from '../../../../assets/iconTelephon.svg?url';
import IconEmail from '../../../../assets/iconEmail.svg?url';
import IconLocation from '../../../../assets/iconLocation.svg?url';
import { Link } from "react-router-dom";
export const AboutContent = () => {
    return (_jsxs("section", { className: container, children: [_jsxs("div", { className: box, children: [_jsx("h2", { className: title, children: "ABOUT US" }), _jsx("p", { className: description, children: "Welcome to NordicNest, where craftsmanship meets elegance. We specialize in high-end, exclusive furniture designed to transform your living spaces into timeless works of art." }), _jsx("p", { className: description, children: "Every piece in our collection is meticulously crafted using premium materials and expert techniques, ensuring exceptional quality, durability, and beauty. Whether you're seeking luxurious sofas, handcrafted dining tables, or bespoke interior solutions, we offer one-of-a-kind designs that reflect sophistication and individuality." }), _jsx("p", { className: description, children: "At NordicNest, we believe that furniture is more than just functional\u2014it\u2019s an expression of style and personality. That\u2019s why we collaborate with renowned designers and skilled artisans to create furniture that is as unique as you are" }), _jsx("p", { className: description, children: "Explore our showroom or browse our online catalog to discover exclusive collections tailored for those who appreciate refined aesthetics and superior craftsmanship." }), _jsxs("div", { className: contactContainer, children: [_jsxs("div", { className: infoBlock, children: [_jsx("img", { className: icon, src: IconLocation, alt: "IconLocation" }), _jsxs("p", { className: text, children: [" Location: ", _jsx(Link, { className: link, to: "https://www.google.com/maps/place/Passeig+de+Garcia+F%C3%A0ria,+81,+Sant+Mart%C3%AD,+08019+Barcelona", children: "Passeig de Garcia F\u00E0ria, 81, Sant Mart\u00ED, 08019 Barcelona" })] })] }), _jsxs("div", { className: infoBlock, children: [_jsx("img", { className: icon, src: IconPhone, alt: "IconPhone" }), _jsxs("p", { className: text, children: ["Contact Us:", _jsx("a", { className: link, href: "tel:+34685090606", children: "+34 685 09 06 06" })] })] }), _jsxs("div", { className: infoBlock, children: [_jsx("img", { className: icon, src: IconEmail, alt: "IconEmail" }), _jsxs("p", { className: text, children: ["Email: ", _jsx("a", { className: link, href: "mailto:nordic_nest@gmail.com", children: "nordic_nest@gmail.com" })] })] }), _jsx("p", { className: text, children: "Let us help you create a home that is truly one of a kind." })] })] }), _jsx("div", { className: box, children: _jsx("img", { className: imageStyle, src: Pexels, alt: "Pexels" }) })] }));
};
export default AboutContent;
